version: '3'
services:
  prisma-test:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4488:4488"
    environment:
      PRISMA_CONFIG: |
        port: 4488
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mytest:/var/lib/mysql
volumes:
  mytest:
